name: smython
description: |
  A subset of Python 3, just large enough to run `fac`.
  Written by Stefan Matthias Aust <eibaan@gmail.com>
version: 0.2.0
repository: https://github.com/sma/dart_smython
environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  coverage: ^1.6.3
  lints: ^3.0.0
  test: ^1.24.0
